---
- name: playbook for httpd
  hosts: ansiblec1,ansiblec2
  tasks:
   - name: task to install apache
     yum:
      name: httpd
      state: latest
   - name: STart the Apache 
     service:
      name: httpd
      state: started
      enabled: yes
   - name: Download the config file
     get_url:
      url: http://loalhost/httpd.conf
      dest: /etc/httpd/conf/httpd.conf
   - name: Index.html
     copy:
      content: "Hello XXX"
      dest: /var/www/html/index.html
      mode: 0644
   - name: lineinfile test
     lineinfile:
      path: /var/www/html/index.html
      regexp: 'Hello XXX'
      line: 'Hello {{ansible_hostname}} '
