---
- name: check a package is installed and print
  hosts: all
  tasks:
   - name: Verify using below command
     shell: rpm -qa |grep mysql
     register: x
   - name: print in jason
     debug: var='x'
   - name: Display yes
     debug: msg="pakage is installed"
     when: x.stdout != ""
   - name: Display no
     debug: msg="Package is not installed"
     when: x.stdout == ""
   - name: gong to install now
     yum:
      name: mariadb
      name: mariadb-server
      state: latest
     when: x.stdout == ""
